// server/config/crypto.js
// Здесь ты вручную задаёшь адреса для приёма крипты.
// Поля "note" видны пользователю на странице оплаты — оставляй их на английском.

module.exports = {
  fiatCurrency: 'USD',
  paymentWindowMinutes: 30,
  rateCacheTtlSeconds: 60,

  rateFallback: {
    USDT: 1.0,
    BTC: 65000,
    ETH: 3200,
  },

  coingeckoIds: {
    USDT: 'tether',
    BTC: 'bitcoin',
    ETH: 'ethereum',
  },

  networks: [
    {
      id: 'usdt_trc20',
      coin: 'USDT',
      network: 'TRC20',
      networkLabel: 'TRON (TRC20)',
      address: 'TLuUZTWmR45Prcjdun5Q16Bbmc5PxozV8J',
      decimals: 2,
      minUsd: 1,
      enabled: true,
      color: '#26a17b',
      note: 'Network fee ~1 USDT',
    },
    {
      id: 'usdt_erc20',
      coin: 'USDT',
      network: 'ERC20',
      networkLabel: 'Ethereum (ERC20)',
      address: '0x02f36e3e0f435762def1cb0a538c758dbf17027f',
      decimals: 2,
      minUsd: 10,
      enabled: true,
      color: '#26a17b',
      note: 'High Ethereum network fee',
    },
    {
      id: 'usdt_bep20',
      coin: 'USDT',
      network: 'BEP20',
      networkLabel: 'BNB Smart Chain (BEP20)',
      address: '0x02f36e3e0f435762def1cb0a538c758dbf17027f',
      decimals: 2,
      minUsd: 1,
      enabled: true,
      color: '#26a17b',
      note: 'Network fee ~0.3 USDT',
    },
    {
      id: 'btc',
      coin: 'BTC',
      network: 'BTC',
      networkLabel: 'Bitcoin',
      address: '3Gso1NV68V2kYs6EoGtjd1FQQG9kUjS8Vs',
      decimals: 8,
      minUsd: 5,
      enabled: true,
      color: '#f7931a',
      note: '',
    },
    {
      id: 'eth_erc20',
      coin: 'ETH',
      network: 'ERC20',
      networkLabel: 'Ethereum (ERC20)',
      address: '0x0022b6813b936E5eF0EE5D058B75C8882cdB7E52',
      decimals: 6,
      minUsd: 10,
      enabled: true,
      color: '#627eea',
      note: 'High Ethereum network fee',
    },
    {
      id: 'eth_bep20',
      coin: 'ETH',
      network: 'BEP20',
      networkLabel: 'BNB Smart Chain (BEP20)',
      address: '0x02f36e3e0f435762def1cb0a538c758dbf17027f',
      decimals: 6,
      minUsd: 5,
      enabled: true,
      color: '#627eea',
      note: 'BEP20-wrapped ETH',
    },
  ],
};